FROM docker.io/library/nginx

WORKDIR /usr/share/nginx/html/

COPY ./nginx.conf /etc/nginx/conf.d/default.conf

# USER nginx

EXPOSE 8080

COPY ./index.php /usr/share/nginx/html/index.php
COPY ./index.html /var/www/html/index.html